# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.0.0"

# Load Ruby Gems:
require 'yaml'

# Environmental Variables:
ENV['TEST_SETTINGS_PATH'] = "./test-settings.yml"
ENV['VERBOSITY'] = 'v'

# Load test servers from file:
settings = YAML.load_file(ENV['TEST_SETTINGS_PATH'])
servers = settings['servers']

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Check for vagrant-vbguest plugin
  if !Vagrant.has_plugin?('vagrant-vbguest')
    puts 'ERROR: vagrant-vbguest plugin required. To install run `vagrant plugin install vagrant-vbguest`'
    abort
  end

  # Necessary for vbguest to work (if box comes with out-of-date kernel)
  config.vbguest.installer_options = {
    allow_kernel_upgrade: true
  }

  ##############################################################
  # Create the test-servers.                                   #
  ##############################################################
  servers.each_with_index do |server, index|

    config.vm.define server['hostname'] do |test|

      # Specify the Vagrant Box, version, and update check:
      test.vm.box = server['box']
      test.vm.box_version = server['box_version']

      # Customize the hostname:
      test.vm.hostname = server['hostname']

      # Customize the forwarded ports:
      test.vm.network "forwarded_port", guest: "80", host: "808#{index}"

      # VirtualBox Provider
      test.vm.provider "virtualbox" do |vb|
        # Customize the number of CPUs on the VM:
        vb.cpus = 2

        # Customize the amount of memory on the VM:
        vb.memory = 4096

        # Customize the name that appears in the VirtualBox GUI:
        vb.name = server['hostname']
      end

      # Run Ansible from the Vagrant host:
      test.vm.provision "ansible", run:"always" do |ansible|
        ansible.host_key_checking = false
        ansible.playbook = "./test-playbook.yml"
        ansible.verbose = ENV['VERBOSITY']
      end

      # Disable the default synced folder:
      test.vm.synced_folder '.', '/vagrant', disabled: true

    end

  end

end