---
# tasks file for molecule_podman
- name: Print OS and distro Ansible variables collected by setup
  debug:
    msg:
      - "ansible_os_family: {{ ansible_os_family }}"
      - "ansible_distribution: {{ ansible_distribution }}"
      - "ansible_distribution_major_version: {{ ansible_distribution_major_version }}"
      - "ansible_distribution_version: {{ ansible_distribution_version }}"
      - "ansible_distribution_release: {{ ansible_distribution_release }}"
- name: Distribution-specific tasks
  include_tasks: "{{ ansible_distribution }}_{{ driver }}.yml"
- name: Create the venv directory if it does not exist
  file:
    path: "{{  venv_path  }}"
    state: directory
- name: Install virtualenv via pip
  pip:
    name: virtualenv
    executable: pip3.9
- name: Set up virtual enviornment with python 3.9
  pip:
    name:
      - molecule
      - ansible-core
      - "molecule-{{  driver  }}"
    virtualenv: "{{  venv_path  }}/venv"
    virtualenv_python: python3.9