---
- name: Install prereq
  apt:
    name: software-properties-common
    state: present
- name: Adicionando PPA do php 7.1
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: present
    validate_certs: no
- name: Install fedora packages
  apt:
    name:
      - python3.9
      - python3-pip
      - libssl-dev
      - podman
    state: present