# conda env create -f environment.yml
name: expanse
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ansible
  - ansible-lint
  - pip:
      - molecule
      - molecule-podman # or molecule-docker
