---
- name: Converge
  hosts: all
  tasks:
    - name: Install sudo
      package:
        name: sudo
        state: present
    - name: "Include chpc.molecule_install"
      include_role:
        name: "chpc.molecule_install"
