name: "Lint Vagrant Ansible Role"

on:
  pull_request:
    branches:
      - main
    paths:
      - examples/vagrant/**
  push:
    branches:
      - main
    paths:
      - examples/vagrant/**

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python packages
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            ansible
            ansible-lint

      - name: Lint Vagrant Example
        working-directory: examples/vagrant
        run: |-
          ansible-lint -p test-playbook.yml
